# ============================== Filebeat inputs ===============================
filebeat.inputs:
- type: container
  paths:
    - '/var/lib/docker/containers/*/*.log'
  processors:
    - decode_json_fields:
        fields: ["message"]
        target: ""
        overwrite_keys: true

fields:
  env: production
  source_type: vast_ai_worker
  instance_id: stable-diffusion-worker-01

# ============================== Outputs =====================================
output.elasticsearch:
  hosts: ["https://elasticsearch.34.142.131.209.nip.io:443"]
  # api_key: "WlJzaU9ab0JGbkE1S2k3czhmV2s6QUlTenZzVTdTSUNSLWtsN2tma2JzUQ=="
  username: "elastic"
  password: "elasticntt19hh"

  ssl.enabled: true

# ============================== Processors =====================================
processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_cloud_metadata: ~