apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: api-gateway-monitor
  namespace: monitor
  labels:
    release: prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - service-dev
  selector:
    matchLabels:
      app: api-gateway
  endpoints:
  - port: http
    path: '/metrics'
    interval: 15s 