apiVersion: v1
kind: Secret
metadata:
    name: {{ .Release.Name }}-secret
type: Opaque
data:
    RABBITMQ_DEFAULT_USER: {{ .Values.rabbitmq.username | b64enc | quote }}
    RABBITMQ_DEFAULT_PASS: {{ .Values.rabbitmq.password | b64enc | quote }}
